Repository woorifisa-projects/i-was-a-car-front, pull requests merged in 2023-09, with the labels that each got.

#21 [feat] 로그인 처리 및 반응형 헤더 구현
  src/apis/index.js
  src/apis/service/auth/authApi.js
  src/layouts/service/default/AppBar.vue
  src/router/service.js
  src/store/app.js
  src/store/auth.js
  src/views/common/NotFoundView.vue
  src/views/service/LoginView.vue
Labels: feature

#24 [release] Sprint 3 - to develop
  src/assets/images/iwasacar.png
Labels: relase

#23 [release] Sprint 3 - to main
  .gitignore
  package-lock.json
  package.json
  src/apis/index.js
  src/apis/service/auth/authApi.js
  src/apis/service/products/productApi.js
  src/assets/admin-logo.png
  src/assets/images/iwasacar.png
  src/assets/images/iwasacarlogo.png
  src/components/Form/BasicForm.vue
  src/components/HomeMain.vue
  src/components/card/Card.vue
  src/components/card/CardBtn.vue
  src/components/card/CardForm.vue
  src/components/card/CardTitle.vue
  src/components/common/BtnBlack.vue
  src/components/common/BtnWhite.vue
  src/components/contract/AgreementCheck.vue
  src/components/data/contract.js
  src/components/products/ProductsList.vue
  src/components/products/Search.vue
  src/components/products/details/BasicCarInfo.vue
  src/components/products/details/CarDiagnosis.vue
  src/components/products/details/FinancialService.vue
  src/components/products/details/ImageSlider.vue
  src/components/products/details/MileageAnalysis.vue
  src/components/products/details/PerformanceCheckIcon.vue
  src/layouts/service/default/AppBar.vue
  src/layouts/service/default/Default.vue
  src/layouts/service/default/Footer.vue
  src/plugins/vuetify.js
  src/router/service.js
  src/store/app.js
  src/store/auth.js
  src/views/common/NotFoundView.vue
  src/views/service/EmailAuthenticationView.vue
  src/views/service/Home.vue
  src/views/service/HomeView.vue
  src/views/service/LoginView.vue
  src/views/service/SignupConsentView.vue
  src/views/service/SignupView.vue
  src/views/service/products/ProductDetails.vue
  src/views/service/purchase/BasicInfoView.vue
  vite.config.js
Labels: relase

#22 [feat] 상품 판매 UI
  index.html
  src/apis/service/histories/saleApi.js
  src/apis/service/products/productApi.js
  src/components/FindAddress.vue
  src/components/card/Card.vue
  src/components/card/CardBtn.vue
  src/components/common/ImageAttach.vue
  src/router/service.js
  src/store/retrieveCar/retrieveCar.js
  src/store/sales/saleStore.js
  src/utils/formdata/multipart.js
  src/utils/images/changeFiles.js
  src/utils/images/changeImageToData.js
  src/utils/images/deleteImage.js
  src/utils/index.js
  src/views/service/products/ProductDetails.vue
  src/views/service/sales/BasicInfo.vue
  src/views/service/sales/CarInfo.vue
  src/views/service/sales/CarRetrieve.vue
  src/views/service/sales/ImageInput.vue
  src/views/service/sales/MeetingLocation.vue
  src/views/service/sales/PriceAndAccount.vue
Labels: feature

#25 [feat] one click purchase
  src/apis/service/contracts/contractApi.js
  src/apis/service/products/productApi.js
  src/components/FindAddress.vue
  src/components/Form/BasicForm.vue
  src/components/Form/CarTypeForm.vue
  src/components/Form/ChoiceCarForm.vue
  src/components/Form/ContractForm.vue
  src/components/Form/DeliveryForm.vue
  src/components/Form/DoneForm.vue
  src/components/Form/FinanceForm.vue
  src/components/Form/ScrollComponent.vue
  src/components/Form/SearchCarForm.vue
  src/components/card/CardForm.vue
  src/components/contract/AgreementCheck.vue
  src/components/data/period.js
  src/components/data/searchCategory.js
  src/components/products/Search.vue
  src/router/service.js
  src/views/service/OneClickPurchaseView.vue
  src/views/service/purchase/CarTypeView.vue
  src/views/service/purchase/ChoiceCarView.vue
  src/views/service/purchase/ContractView.vue
  src/views/service/purchase/DeliveryView.vue
  src/views/service/purchase/DoneView.vue
  src/views/service/purchase/InsurancesView.vue
  src/views/service/purchase/LoansView.vue
  src/views/service/purchase/SearchCarView.vue
Labels: feature

#26 [refactor] 충돌 해결
  src/apis/service/products/productApi.js
  src/components/FindAddress.vue
  src/components/Form/CompleteForm.vue
  src/views/service/purchase/DoneView.vue
  src/views/service/purchase/SearchCarView.vue
Labels: refactor

#27 [feat] 관리자 페이지 네비게이션 구현
  src/assets/admin-logo.png
  src/layouts/admin/default/TheSidebar.vue
  src/router/admin.js
  src/views/admin/members/MemberManagementView.vue
  src/views/admin/products/ProductJudgeManagementView.vue
  src/views/admin/products/ProductManagementView.vue
Labels: feature, admin

#28 [feat] my page tab 기능 구현
  src/apis/service/histories/historyApi.js
  src/apis/service/histories/memberInfoApi.js
  src/assets/images/admin-logo.png
  src/assets/images/iwasacar.png
  src/layouts/service/myPage/AppBar.vue
  src/layouts/service/myPage/Default.vue
  src/layouts/service/myPage/View.vue
  src/plugins/vuetify.js
  src/router/service.js
  src/views/service/mypage/MemberInfoView.vue
  src/views/service/mypage/PurchaseHistoryDetailView.vue
  src/views/service/mypage/PurchaseHistoryView.vue
  src/views/service/mypage/SaleHistoryDetailView.vue
  src/views/service/mypage/SaleHistoryView.vue
Labels: feature

#29 [feat] search 검색 기능 구현
  src/apis/service/products/productApi.js
  src/components/card/Card.vue
  src/components/card/CardBtn.vue
  src/components/products/Search.vue
  src/router/service.js
  src/views/service/HomeView.vue
  src/views/service/purchase/BasicInfoView.vue
  src/views/service/purchase/CarTypeView.vue
  src/views/service/purchase/ChoiceCarView.vue
  src/views/service/purchase/ContractView.vue
  src/views/service/purchase/DeliveryView.vue
  src/views/service/purchase/DoneView.vue
  src/views/service/purchase/InsurancesView.vue
  src/views/service/purchase/LoansView.vue
  src/views/service/purchase/SearchCarView.vue
Labels: feature

#32 [refactor]/회원 상세페이지 수정
  src/layouts/service/myPage/Default.vue
  src/views/service/mypage/MemberInfoView.vue
Labels: feature

#34 [refactor] 상품판매 API 연결
  src/apis/service/histories/sales/saleApi.js
  src/components/Form/ContractForm.vue
  src/components/HomeMain.vue
  src/components/card/CardBtn.vue
  src/components/common/BtnWhite.vue
  src/router/service.js
  src/store/sales/saleStore.js
  src/utils/formdata/dateFormat.js
  src/utils/formdata/multipart.js
  src/utils/images/changeFiles.js
  src/utils/index.js
  src/views/service/sales/BasicInfo.vue
  src/views/service/sales/CarInfo.vue
  src/views/service/sales/CarRetrieve.vue
  src/views/service/sales/ContractView.vue
  src/views/service/sales/DoneView.vue
  src/views/service/sales/ImageInput.vue
  src/views/service/sales/MeetingLocation.vue
  src/views/service/sales/OneClickSaleView.vue
  src/views/service/sales/PriceAndAccount.vue
Labels: feature, refactor

#35 [feat] 인증/인가 API 연동
  src/App.vue
  src/apis/service/auth/authApi.js
  src/layouts/service/default/AppBar.vue
  src/router/index.js
  src/router/service.js
  src/store/auth.js
  src/views/service/EmailAuthenticationView.vue
  src/views/service/LoginView.vue
  src/views/service/SignupView.vue
Labels: feature

#38 [refactor] 판매 폼 유효성 검사
  src/components/FindAddress.vue
  src/components/HomeMain.vue
  src/components/card/Card.vue
  src/components/card/CardBtn.vue
  src/components/common/ImageAttach.vue
  src/store/btnStore.js
  src/store/retrieveCar/retrieveCar.js
  src/store/sales/saleStore.js
  src/store/sales/saleValidateStore.js
  src/views/service/sales/CarInfo.vue
  src/views/service/sales/CarRetrieve.vue
  src/views/service/sales/ContractView.vue
  src/views/service/sales/DoneView.vue
  src/views/service/sales/ImageInput.vue
  src/views/service/sales/MeetingLocation.vue
  src/views/service/sales/PriceAndAccount.vue
Labels: refactor

#40 [feat] 유효성 검증 및 기타 등등
  src/components/HomeMain.vue
  src/components/card/Card.vue
  src/components/card/CardBtn.vue
  src/components/card/CardForm.vue
  src/components/card/CardTitle.vue
  src/components/common/BtnBlack.vue
  src/components/service/Dialog.vue
  src/layouts/admin/default/TheSidebar.vue
  src/layouts/common/AppBar.vue
  src/layouts/service/default/Default.vue
  src/layouts/service/myPage/AppBar.vue
  src/layouts/service/myPage/Default.vue
  src/router/service.js
  src/views/service/EmailAuthenticationView.vue
  src/views/service/LoginView.vue
  src/views/service/SignupConsentView.vue
  src/views/service/SignupView.vue
Labels: feature

#42 [style] 전반적인 UI 스타일 변경
  src/components/Form/BasicForm.vue
  src/components/Form/CarTypeForm.vue
  src/components/Form/ChoiceCarForm.vue
  src/components/Form/ScrollComponent.vue
  src/components/products/details/BasicCarInfo.vue
  src/components/products/details/CarDiagnosis.vue
  src/components/products/details/FinancialService.vue
  src/components/products/details/ImageSlider.vue
  src/components/products/details/MileageAnalysis.vue
  src/components/service/Dialog.vue
  src/layouts/service/myPage/Default.vue
  src/views/service/SignupConsentView.vue
  src/views/service/mypage/MemberInfoView.vue
  src/views/service/mypage/PurchaseHistoryDetailView.vue
  src/views/service/mypage/PurchaseHistoryView.vue
  src/views/service/mypage/SaleHistoryDetailView.vue
  src/views/service/mypage/SaleHistoryView.vue
  src/views/service/products/ProductDetails.vue
Labels: feature, refactor

#37 [feat] 원클릭 구매 백엔드 연결
  src/apis/service/contracts/contractApi.js
  src/apis/service/histories/purchase/purchaseApi.js
  src/apis/service/histories/sales/saleApi.js
  src/components/Form/BasicForm.vue
  src/components/Form/CarTypeForm.vue
  src/components/Form/ChoiceCarForm.vue
  src/components/Form/ContractForm.vue
  src/components/Form/DeliveryForm.vue
  src/components/Form/FinanceForm.vue
  src/components/Form/ScrollComponent.vue
  src/components/Form/SearchCarForm.vue
  src/components/card/Card.vue
  src/components/card/CardBtn.vue
  src/components/products/details/BasicCarInfo.vue
  src/store/auth.js
  src/store/btnStore.js
  src/store/contractStore.js
  src/store/purchase/purchaseStore.js
  src/views/service/PurchaseView.vue
  src/views/service/purchase/BasicInfoView.vue
  src/views/service/purchase/CarTypeView.vue
  src/views/service/purchase/ChoiceCarView.vue
  src/views/service/purchase/ContractView.vue
  src/views/service/purchase/DeliveryView.vue
  src/views/service/purchase/SearchCarView.vue
  src/views/service/sales/DoneView.vue
  src/views/service/sales/PriceAndAccount.vue
Labels: feature

#36 [feat] admin 페이지 구현
  src/apis/admin/logss/logAPI.js
  src/apis/admin/member/memberAPI.js
  src/views/admin/logs/LogManagementView.vue
  src/views/admin/members/MemberManagementView.vue
Labels: feature

#43 [feat] 일반구매 연결
  src/components/Form/ChoiceCarForm.vue
  src/components/Form/FinanceForm.vue
  src/components/Form/SearchCarForm.vue
  src/components/service/Dialog.vue
Labels: feature

#44 [feat] 관리자 상품 페이지 (전체, 상세)조회 개발
  src/apis/admin/products/productAPI.js
  src/components/admin/products/ImageInsert.vue
  src/components/admin/products/ImageSliderEdit.vue
  src/components/admin/products/MemberInfo.vue
  src/components/admin/products/UpdateCarInfo.vue
  src/components/common/ImageAttach.vue
  src/components/products/details/CarDiagnosis.vue
  src/layouts/admin/default/TheSidebar.vue
  src/router/admin.js
  src/views/admin/logs/LogManagementView.vue
  src/views/admin/products/ProductDetailView.vue
  src/views/admin/products/ProductJudgeManagementView.vue
  src/views/admin/products/ProductManagementView.vue
Labels: feature

#45 [fix] npm run build 오류 해결
  src/layouts/admin/default/TheSidebar.vue
Labels: bug

#46 [refactor] 반응형 UI 수정 및 기타 등등
  src/apis/index.js
  src/components/Form/ChoiceCarForm.vue
  src/components/HomeMain.vue
  src/components/common/ProgressSprinner.vue
  src/components/products/ProductsList.vue
  src/components/products/Search.vue
  src/components/products/details/BasicCarInfo.vue
  src/components/products/details/CarDiagnosis.vue
  src/components/products/details/FinancialService.vue
  src/components/products/details/ImageSlider.vue
  src/components/products/details/MileageAnalysis.vue
  src/layouts/common/AppBar.vue
  src/layouts/service/default/Footer.vue
  src/layouts/service/myPage/Default.vue
  src/store/loading.js
  src/views/service/HomeView.vue
  src/views/service/mypage/MemberInfoView.vue
  src/views/service/mypage/PurchaseHistoryView.vue
  src/views/service/mypage/SaleHistoryView.vue
  src/views/service/products/ProductDetails.vue
  src/views/service/sales/ContractView.vue
Labels: refactor

#47 [feat] 문서 동의 내역 연결
  src/apis/service/contracts/contractApi.js
  src/components/Form/BasicForm.vue
  src/components/Form/ChoiceCarForm.vue
  src/components/Form/ContractForm.vue
  src/components/card/CardBtn.vue
  src/router/service.js
  src/store/contractStore.js
  src/store/sales/saleStore.js
  src/views/service/OneClickPurchaseView.vue
  src/views/service/OneClickSaleView.vue
  src/views/service/PurchaseView.vue
  src/views/service/common/BasicInfoView.vue
  src/views/service/common/DoneView.vue
  src/views/service/purchase/ChoiceCarView.vue
  src/views/service/purchase/ContractView.vue
  src/views/service/sales/BasicInfo.vue
  src/views/service/sales/CarInfoView.vue
  src/views/service/sales/CarRetrieveView.vue
  src/views/service/sales/ContractView.vue
  src/views/service/sales/DoneView.vue
  src/views/service/sales/ImageInputView.vue
  src/views/service/sales/MeetingView.vue
  src/views/service/sales/OneClickSaleView.vue
  src/views/service/sales/PriceAndAccountView.vue
Labels: feature

#49 [fix] merge 후 issue 해결
  src/components/products/details/CarDiagnosis.vue
  src/views/service/mypage/MemberInfoView.vue
Labels: bug, hotfix

#48 [Refactor] 차량 조회 시 UI 수정
  src/components/products/details/CarDiagnosis.vue
  src/views/service/PurchaseView.vue
  src/views/service/purchase/DeliveryView.vue
  src/views/service/sales/CarInfoView.vue
  src/views/service/sales/MeetingView.vue
Labels: refactor

#52 [hotfix] 뒤로가기 시 가격 오류 수정
  src/components/common/ImageAttach.vue
  src/views/service/OneClickSaleView.vue
  src/views/service/sales/ContractView.vue
  src/views/service/sales/PriceAndAccountView.vue
Labels: hotfix

#53 [fix] 버튼 눌렀을 시 발생하는 오류 해결
  src/apis/admin/products/productAPI.js
  src/components/admin/products/UpdateCarInfo.vue
  src/components/common/BtnBlack.vue
Labels: bug

#54 [refactor] router 마이페이지로 이동
  src/components/Form/ChoiceCarForm.vue
  src/components/card/Card.vue
  src/components/card/CardBtn.vue
  src/store/purchase/purchaseStore.js
  src/store/sales/saleStore.js
  src/views/service/OneClickPurchaseView.vue
  src/views/service/OneClickSaleView.vue
  src/views/service/PurchaseView.vue
  src/views/service/common/DoneView.vue
  src/views/service/mypage/SaleHistoryView.vue
  src/views/service/purchase/ContractView.vue
  src/views/service/sales/ContractView.vue
  src/views/service/sales/MeetingView.vue
Labels: refactor

#55 [refactor] UI 수정 및 기타 등등
  index.html
  src/components/Form/BasicForm.vue
  src/components/Form/ChoiceCarForm.vue
  src/components/Form/ScrollComponent.vue
  src/components/HomeMain.vue
  src/components/admin/products/ImageSliderEdit.vue
  src/components/admin/products/MemberInfo.vue
  src/components/admin/products/UpdateCarInfo.vue
  src/components/products/Search.vue
  src/components/products/details/BasicCarInfo.vue
  src/components/products/details/CarDiagnosis.vue
  src/components/products/details/ImageSlider.vue
  src/layouts/common/AppBar.vue
  src/store/sales/saleStore.js
  src/views/admin/logs/LogManagementView.vue
  src/views/admin/members/MemberManagementView.vue
  src/views/admin/products/ProductDetailView.vue
  src/views/admin/products/ProductJudgeManagementView.vue
  src/views/admin/products/ProductManagementView.vue
  src/views/service/EmailAuthenticationView.vue
  src/views/service/LoginView.vue
  src/views/service/OneClickSaleView.vue
  src/views/service/mypage/MemberInfoView.vue
  src/views/service/products/ProductDetails.vue
  src/views/service/purchase/ChoiceCarView.vue
  src/views/service/purchase/ContractView.vue
  src/views/service/purchase/DeliveryView.vue
  src/views/service/sales/MeetingView.vue
Labels: feature, refactor

#58 [Release] Sprint-5-2 to develop
  src/apis/service/contracts/contractApi.js
  src/apis/service/histories/sales/saleApi.js
  src/components/card/CardBtn.vue
  src/components/common/BtnBlack.vue
  src/store/auth.js
  src/store/btnStore.js
  src/store/sales/saleStore.js
  src/views/service/SignupConsentView.vue
  src/views/service/mypage/PurchaseHistoryView.vue
  src/views/service/purchase/BasicInfoView.vue
  src/views/service/purchase/DoneView.vue
  src/views/service/sales/BasicInfo.vue
  src/views/service/sales/CarInfo.vue
  src/views/service/sales/CarRetrieve.vue
  src/views/service/sales/DoneView.vue
  src/views/service/sales/ImageInput.vue
  src/views/service/sales/MeetingLocation.vue
  src/views/service/sales/OneClickSaleView.vue
  src/views/service/sales/PriceAndAccount.vue
Labels: relase

#60 README.md
  README.md
Labels: documentation

#61 [Refactor] 마이페이지 및 기타 등등
  src/components/products/details/BasicCarInfo.vue
  src/layouts/service/myPage/Default.vue
  src/layouts/service/myPage/View.vue
  src/router/index.js
  src/router/service.js
  src/store/route.js
  src/views/service/SignupConsentView.vue
  src/views/service/SignupView.vue
  src/views/service/mypage/MemberInfoView.vue
Labels: refactor

#62 [feat] 구매 판매 유효성 완료 및 API 마지막에 쏘는 걸로 합치기
  src/apis/service/contracts/contractApi.js
  src/components/Form/BasicForm.vue
  src/components/Form/CarTypeForm.vue
  src/components/Form/ChoiceCarForm.vue
  src/components/Form/DeliveryForm.vue
  src/components/Form/FinanceForm.vue
  src/components/Form/ScrollComponent.vue
  src/components/Form/SearchCarForm.vue
  src/components/card/CardBtn.vue
  src/store/purchase/purchaseStore.js
  src/store/sales/saleStore.js
  src/store/sales/saleValidateStore.js
  src/views/service/OneClickPurchaseView.vue
  src/views/service/OneClickSaleView.vue
  src/views/service/common/DoneView.vue
  src/views/service/purchase/BasicInfoView.vue
  src/views/service/purchase/CarTypeView.vue
  src/views/service/purchase/ChoiceCarView.vue
  src/views/service/purchase/ContractView.vue
  src/views/service/purchase/DeliveryView.vue
  src/views/service/purchase/DoneView.vue
  src/views/service/sales/BasicInfo.vue
  src/views/service/sales/CarInfo.vue
  src/views/service/sales/CarRetrieve.vue
  src/views/service/sales/ContractView.vue
  src/views/service/sales/DoneView.vue
  src/views/service/sales/ImageInput.vue
  src/views/service/sales/MeetingLocation.vue
  src/views/service/sales/MeetingView.vue
  src/views/service/sales/OneClickSaleView.vue
  src/views/service/sales/PriceAndAccount.vue
  src/views/service/sales/PriceAndAccountView.vue
Labels: feature

#63 [bug] 검색 관련 오류 수정
  src/components/contract/AgreementCheck.vue
  src/components/data/searchCategory.js
  src/components/products/Search.vue
  src/views/service/HomeView.vue
Labels: bug

#64 fix : 관리자 페이지 조회 수정
  src/apis/admin/products/productAPI.js
  src/views/admin/products/ProductDetailView.vue
Labels: bug

#65 [hotfix] admin router 처리
  src/apis/admin/logss/logAPI.js
  src/apis/admin/member/memberAPI.js
  src/router/admin.js
  src/router/index.js
  src/router/service.js
  src/store/auth.js
Labels: hotfix

#70 release develop
  src/components/Form/CarTypeForm.vue
  src/components/Form/FinanceForm.vue
  src/components/card/CardBtn.vue
  src/views/service/SignupView.vue
  src/views/service/purchase/CarTypeView.vue
  src/views/service/purchase/ChoiceCarView.vue
  src/views/service/purchase/DeliveryView.vue
  src/views/service/sales/PriceAndAccountView.vue
Labels: relase

#69 release to main
  README.md
  src/apis/admin/logss/logAPI.js
  src/apis/admin/member/memberAPI.js
  src/apis/admin/products/productAPI.js
  src/apis/service/contracts/contractApi.js
  src/components/Form/BasicForm.vue
  src/components/Form/CarTypeForm.vue
  src/components/Form/ChoiceCarForm.vue
  src/components/Form/DeliveryForm.vue
  src/components/Form/FinanceForm.vue
  src/components/Form/ScrollComponent.vue
  src/components/Form/SearchCarForm.vue
  src/components/admin/products/UpdateCarInfo.vue
  src/components/card/CardBtn.vue
  src/components/common/ProgressSprinner.vue
  src/components/contract/AgreementCheck.vue
  src/components/data/searchCategory.js
  src/components/products/Search.vue
  src/components/products/details/BasicCarInfo.vue
  src/components/products/details/CarDiagnosis.vue
  src/layouts/service/myPage/Default.vue
  src/layouts/service/myPage/View.vue
  src/router/admin.js
  src/router/index.js
  src/router/service.js
  src/store/auth.js
  src/store/purchase/purchaseStore.js
  src/store/route.js
  src/store/sales/saleStore.js
  src/store/sales/saleValidateStore.js
  src/views/admin/products/ProductDetailView.vue
  src/views/service/HomeView.vue
  src/views/service/OneClickPurchaseView.vue
  src/views/service/OneClickSaleView.vue
  src/views/service/SignupConsentView.vue
  src/views/service/SignupView.vue
  src/views/service/common/DoneView.vue
  src/views/service/mypage/MemberInfoView.vue
  src/views/service/mypage/PurchaseHistoryView.vue
  src/views/service/mypage/SaleHistoryView.vue
  src/views/service/purchase/BasicInfoView.vue
  src/views/service/purchase/CarTypeView.vue
  src/views/service/purchase/ContractView.vue
  src/views/service/purchase/DeliveryView.vue
  src/views/service/purchase/DoneView.vue
  src/views/service/sales/BasicInfo.vue
  src/views/service/sales/CarInfo.vue
  src/views/service/sales/CarInfoView.vue
  src/views/service/sales/CarRetrieve.vue
  src/views/service/sales/ContractView.vue
  src/views/service/sales/DoneView.vue
  src/views/service/sales/ImageInput.vue
  src/views/service/sales/MeetingLocation.vue
  src/views/service/sales/MeetingView.vue
  src/views/service/sales/OneClickSaleView.vue
  src/views/service/sales/PriceAndAccount.vue
  src/views/service/sales/PriceAndAccountView.vue
  vite.config.js
Labels: relase

#71 hotfix
  src/components/Form/BasicForm.vue
  src/components/Form/CarTypeForm.vue
  src/components/Form/ChoiceCarForm.vue
  src/components/Form/ContractForm.vue
  src/components/Form/FinanceForm.vue
  src/components/Form/ScrollComponent.vue
  src/components/Form/SearchCarForm.vue
  src/components/admin/products/UpdateCarInfo.vue
  src/components/card/CardBtn.vue
  src/components/products/Search.vue
  src/components/products/details/BasicCarInfo.vue
  src/components/products/details/CarDiagnosis.vue
  src/components/service/Dialog.vue
  src/layouts/admin/default/TheSidebar.vue
  src/layouts/common/AppBar.vue
  src/layouts/service/myPage/Default.vue
  src/views/service/EmailAuthenticationView.vue
  src/views/service/LoginView.vue
  src/views/service/OneClickPurchaseView.vue
  src/views/service/PurchaseView.vue
  src/views/service/SignupConsentView.vue
  src/views/service/SignupView.vue
  src/views/service/common/BasicInfoView.vue
  src/views/service/mypage/MemberInfoView.vue
  src/views/service/mypage/PurchaseHistoryDetailView.vue
  src/views/service/mypage/PurchaseHistoryView.vue
  src/views/service/mypage/SaleHistoryDetailView.vue
  src/views/service/mypage/SaleHistoryView.vue
  src/views/service/products/ProductDetails.vue
  src/views/service/purchase/CarTypeView.vue
  src/views/service/purchase/ChoiceCarView.vue
  src/views/service/purchase/ContractView.vue
  src/views/service/purchase/DeliveryView.vue
  src/views/service/purchase/SearchCarView.vue
  src/views/service/sales/CarInfoView.vue
  src/views/service/sales/CarRetrieveView.vue
  src/views/service/sales/ContractView.vue
  src/views/service/sales/ImageInputView.vue
  src/views/service/sales/MeetingView.vue
Labels: hotfix

#72 hotfix
  src/views/service/sales/PriceAndAccountView.vue
Labels: hotfix

#73 release to main
  src/components/Form/BasicForm.vue
  src/components/Form/CarTypeForm.vue
  src/components/Form/ChoiceCarForm.vue
  src/components/Form/ContractForm.vue
  src/components/Form/FinanceForm.vue
  src/components/Form/ScrollComponent.vue
  src/components/Form/SearchCarForm.vue
  src/components/admin/products/UpdateCarInfo.vue
  src/components/card/CardBtn.vue
  src/components/products/Search.vue
  src/components/products/details/BasicCarInfo.vue
  src/components/products/details/CarDiagnosis.vue
  src/components/service/Dialog.vue
  src/layouts/admin/default/TheSidebar.vue
  src/layouts/common/AppBar.vue
  src/layouts/service/myPage/Default.vue
  src/views/service/EmailAuthenticationView.vue
  src/views/service/LoginView.vue
  src/views/service/OneClickPurchaseView.vue
  src/views/service/PurchaseView.vue
  src/views/service/SignupConsentView.vue
  src/views/service/SignupView.vue
  src/views/service/common/BasicInfoView.vue
  src/views/service/mypage/MemberInfoView.vue
  src/views/service/mypage/PurchaseHistoryDetailView.vue
  src/views/service/mypage/PurchaseHistoryView.vue
  src/views/service/mypage/SaleHistoryDetailView.vue
  src/views/service/mypage/SaleHistoryView.vue
  src/views/service/products/ProductDetails.vue
  src/views/service/purchase/CarTypeView.vue
  src/views/service/purchase/ChoiceCarView.vue
  src/views/service/purchase/ContractView.vue
  src/views/service/purchase/SearchCarView.vue
  src/views/service/sales/CarInfoView.vue
  src/views/service/sales/CarRetrieveView.vue
  src/views/service/sales/ContractView.vue
  src/views/service/sales/ImageInputView.vue
  src/views/service/sales/MeetingView.vue
  src/views/service/sales/PriceAndAccountView.vue
Labels: relase
